Repository acemod/docker-reforger, pull requests merged in 2023-11, with the labels that each got.

#20 Update compose for 0.9.9 config
  docker-compose.yml
Labels: documentation

#11 Add parameters for basic handling of mods
  Dockerfile
  README.md
  docker-compose.yml
  launch.py
Labels: enhancement

#25 Change autogenerated adminPassword from 3 to 2 words
  launch.py
Labels: bug

#26 Prevent duplicates in config mod definitions
  launch.py
Labels: bug

#29 Draft: Fix incorrect version format regexp
  launch.py
Labels: bug

#27 Add support for admins config property, remove edge tag
  Dockerfile
  docker-compose.yml
  docker_default.json
  launch.py
Labels: enhancement
